
on: 
  pull_request:
  issue_comment:
    types: [created, edited]

jobs:
  pr_commented:
    runs-on: ubuntu-latest
    name: PR comment
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
