name: Main Workflow
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Github API Request
      if: github.event.comment.body == 'ok to test'
      id: request
      uses: octokit/request-action@v2.0.2
      with:
        route: ${{ github.event.issue.pull_request.url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Checkout PR Branch
      if: github.event.comment.body == 'ok to test'
      run: |
          echo Hello
          
    - name: Testing
      if: github.event.comment.body == 'ok to test'
      run: echo test
