name: Main Workflow
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    name: PR comment
    steps:
      - run: echo ${{ github.event.comment.body }}
