name: Example

on: 
  pull_request:
  issue_comment:
    types: [created, edited]

jobs:
  pr_commented:
    runs-on: ubuntu-latest
    name: PR comment
    steps:
      - name: Checkout
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"
