name: Main Workflow
on:
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.comment.body, 'ok to test')"
    steps:          
    - name: Testing
      run: echo test
